export interface District {
  id: string;
  name: string;
  isSelected: boolean;
}

export interface Neighborhood {
  id: string;
  name: string;
  isSelected: boolean;
  districtId: string;
}

export const SEOUL_DISTRICTS: District[] = [
  { id: "1", name: "강남구", isSelected: false },
  { id: "2", name: "강동구", isSelected: false },
  { id: "3", name: "강북구", isSelected: false },
  { id: "4", name: "강서구", isSelected: false },
  { id: "5", name: "관악구", isSelected: false },
  { id: "6", name: "광진구", isSelected: false },
  { id: "7", name: "구로구", isSelected: false },
  { id: "8", name: "금천구", isSelected: false },
  { id: "9", name: "노원구", isSelected: false },
  { id: "10", name: "도봉구", isSelected: false },
  { id: "11", name: "동대문구", isSelected: false },
  { id: "12", name: "동작구", isSelected: false },
  { id: "13", name: "마포구", isSelected: false },
  { id: "14", name: "서대문구", isSelected: false },
  { id: "15", name: "서초구", isSelected: false },
  { id: "16", name: "성동구", isSelected: false },
  { id: "17", name: "성북구", isSelected: false },
  { id: "18", name: "송파구", isSelected: false },
  { id: "19", name: "양천구", isSelected: false },
  { id: "20", name: "영등포구", isSelected: false },
  { id: "21", name: "용산구", isSelected: false },
  { id: "22", name: "은평구", isSelected: false },
  { id: "23", name: "종로구", isSelected: false },
  { id: "24", name: "중구", isSelected: false },
  { id: "25", name: "중랑구", isSelected: false },
];

export const SEOUL_NEIGHBORHOODS: Neighborhood[] = [
  // 강남구 (id: "1")
  { id: "1", name: "개포동", isSelected: false, districtId: "1" },
  { id: "2", name: "논현동", isSelected: false, districtId: "1" },
  { id: "3", name: "대치동", isSelected: false, districtId: "1" },
  { id: "4", name: "도곡동", isSelected: false, districtId: "1" },
  { id: "5", name: "삼성동", isSelected: false, districtId: "1" },
  { id: "6", name: "세곡동", isSelected: false, districtId: "1" },
  { id: "7", name: "수서동", isSelected: false, districtId: "1" },
  { id: "8", name: "신사동", isSelected: false, districtId: "1" },
  { id: "9", name: "압구정동", isSelected: false, districtId: "1" },
  { id: "10", name: "역삼동", isSelected: false, districtId: "1" },
  { id: "11", name: "일원동", isSelected: false, districtId: "1" },
  { id: "12", name: "자곡동", isSelected: false, districtId: "1" },
  { id: "13", name: "청담동", isSelected: false, districtId: "1" },

  // 강동구 (id: "2")
  { id: "14", name: "강일동", isSelected: false, districtId: "2" },
  { id: "15", name: "고덕동", isSelected: false, districtId: "2" },
  { id: "16", name: "길동", isSelected: false, districtId: "2" },
  { id: "17", name: "둔촌동", isSelected: false, districtId: "2" },
  { id: "18", name: "명일동", isSelected: false, districtId: "2" },
  { id: "19", name: "상일동", isSelected: false, districtId: "2" },
  { id: "20", name: "성내동", isSelected: false, districtId: "2" },
  { id: "21", name: "암사동", isSelected: false, districtId: "2" },
  { id: "22", name: "천호동", isSelected: false, districtId: "2" },

  // 강북구 (id: "3")
  { id: "23", name: "미아동", isSelected: false, districtId: "3" },
  { id: "24", name: "번동", isSelected: false, districtId: "3" },
  { id: "25", name: "수유동", isSelected: false, districtId: "3" },
  { id: "26", name: "우이동", isSelected: false, districtId: "3" },
  { id: "27", name: "인수동", isSelected: false, districtId: "3" },

  // 강서구 (id: "4")
  { id: "28", name: "가양동", isSelected: false, districtId: "4" },
  { id: "29", name: "개화동", isSelected: false, districtId: "4" },
  { id: "30", name: "공항동", isSelected: false, districtId: "4" },
  { id: "31", name: "과해동", isSelected: false, districtId: "4" },
  { id: "32", name: "귀포동", isSelected: false, districtId: "4" },
  { id: "33", name: "내발산동", isSelected: false, districtId: "4" },
  { id: "34", name: "마곡동", isSelected: false, districtId: "4" },
  { id: "35", name: "방화동", isSelected: false, districtId: "4" },
  { id: "36", name: "외발산동", isSelected: false, districtId: "4" },
  { id: "37", name: "염창동", isSelected: false, districtId: "4" },
  { id: "38", name: "오곡동", isSelected: false, districtId: "4" },
  { id: "39", name: "오쇠동", isSelected: false, districtId: "4" },
  { id: "40", name: "화곡동", isSelected: false, districtId: "4" },

  // 관악구 (id: "5")
  { id: "41", name: "남현동", isSelected: false, districtId: "5" },
  { id: "42", name: "난곡동", isSelected: false, districtId: "5" },
  { id: "43", name: "난향동", isSelected: false, districtId: "5" },
  { id: "44", name: "대학동", isSelected: false, districtId: "5" },
  { id: "45", name: "도림동", isSelected: false, districtId: "5" },
  { id: "46", name: "미성동", isSelected: false, districtId: "5" },
  { id: "47", name: "봉천동", isSelected: false, districtId: "5" },
  { id: "48", name: "사당동", isSelected: false, districtId: "5" },
  { id: "49", name: "서원동", isSelected: false, districtId: "5" },
  { id: "50", name: "성현동", isSelected: false, districtId: "5" },
  { id: "51", name: "신림동", isSelected: false, districtId: "5" },
  { id: "52", name: "은천동", isSelected: false, districtId: "5" },
  { id: "53", name: "인헌동", isSelected: false, districtId: "5" },
  { id: "54", name: "중앙동", isSelected: false, districtId: "5" },
  { id: "55", name: "청림동", isSelected: false, districtId: "5" },
  { id: "56", name: "청룡동", isSelected: false, districtId: "5" },

  // 광진구 (id: "6")
  { id: "57", name: "광장동", isSelected: false, districtId: "6" },
  { id: "58", name: "구의동", isSelected: false, districtId: "6" },
  { id: "59", name: "군자동", isSelected: false, districtId: "6" },
  { id: "60", name: "능동", isSelected: false, districtId: "6" },
  { id: "61", name: "자양동", isSelected: false, districtId: "6" },
  { id: "62", name: "중곡동", isSelected: false, districtId: "6" },
  { id: "63", name: "화양동", isSelected: false, districtId: "6" },

  // 구로구 (id: "7")
  { id: "64", name: "가리봉동", isSelected: false, districtId: "7" },
  { id: "65", name: "개봉동", isSelected: false, districtId: "7" },
  { id: "66", name: "고척동", isSelected: false, districtId: "7" },
  { id: "67", name: "구로동", isSelected: false, districtId: "7" },
  { id: "68", name: "궁동", isSelected: false, districtId: "7" },
  { id: "69", name: "신도림동", isSelected: false, districtId: "7" },
  { id: "70", name: "오류동", isSelected: false, districtId: "7" },
  { id: "71", name: "온수동", isSelected: false, districtId: "7" },
  { id: "72", name: "천왕동", isSelected: false, districtId: "7" },
  { id: "73", name: "항동", isSelected: false, districtId: "7" },

  // 금천구 (id: "8")
  { id: "74", name: "가산동", isSelected: false, districtId: "8" },
  { id: "75", name: "독산동", isSelected: false, districtId: "8" },
  { id: "76", name: "시흥동", isSelected: false, districtId: "8" },

  // 노원구 (id: "9")
  { id: "77", name: "공릉동", isSelected: false, districtId: "9" },
  { id: "78", name: "상계동", isSelected: false, districtId: "9" },
  { id: "79", name: "월계동", isSelected: false, districtId: "9" },
  { id: "80", name: "중계동", isSelected: false, districtId: "9" },
  { id: "81", name: "하계동", isSelected: false, districtId: "9" },

  // 도봉구 (id: "10")
  { id: "82", name: "방학동", isSelected: false, districtId: "10" },
  { id: "83", name: "쌍문동", isSelected: false, districtId: "10" },
  { id: "84", name: "창동", isSelected: false, districtId: "10" },
  { id: "85", name: "도봉동", isSelected: false, districtId: "10" },

  // 동대문구 (id: "11")
  { id: "86", name: "답십리동", isSelected: false, districtId: "11" },
  { id: "87", name: "신설동", isSelected: false, districtId: "11" },
  { id: "88", name: "용신동", isSelected: false, districtId: "11" },
  { id: "89", name: "이문동", isSelected: false, districtId: "11" },
  { id: "90", name: "장안동", isSelected: false, districtId: "11" },
  { id: "91", name: "전농동", isSelected: false, districtId: "11" },
  { id: "92", name: "제기동", isSelected: false, districtId: "11" },
  { id: "93", name: "청량리동", isSelected: false, districtId: "11" },
  { id: "94", name: "회기동", isSelected: false, districtId: "11" },
  { id: "95", name: "휘경동", isSelected: false, districtId: "11" },

  // 동작구 (id: "12")
  { id: "96", name: "노량진동", isSelected: false, districtId: "12" },
  { id: "97", name: "대방동", isSelected: false, districtId: "12" },
  { id: "98", name: "동작동", isSelected: false, districtId: "12" },
  { id: "99", name: "본동", isSelected: false, districtId: "12" },
  { id: "100", name: "사당동", isSelected: false, districtId: "12" },
  { id: "101", name: "상도동", isSelected: false, districtId: "12" },
  { id: "102", name: "신대방동", isSelected: false, districtId: "12" },
  { id: "103", name: "흑석동", isSelected: false, districtId: "12" },

  // 마포구 (id: "13")
  { id: "104", name: "공덕동", isSelected: false, districtId: "13" },
  { id: "105", name: "구수동", isSelected: false, districtId: "13" },
  { id: "106", name: "노고산동", isSelected: false, districtId: "13" },
  { id: "107", name: "대흥동", isSelected: false, districtId: "13" },
  { id: "108", name: "도화동", isSelected: false, districtId: "13" },
  { id: "109", name: "동교동", isSelected: false, districtId: "13" },
  { id: "110", name: "마포동", isSelected: false, districtId: "13" },
  { id: "111", name: "망원동", isSelected: false, districtId: "13" },
  { id: "112", name: "상수동", isSelected: false, districtId: "13" },
  { id: "113", name: "상암동", isSelected: false, districtId: "13" },
  { id: "114", name: "서강동", isSelected: false, districtId: "13" },
  { id: "115", name: "서교동", isSelected: false, districtId: "13" },
  { id: "116", name: "성산동", isSelected: false, districtId: "13" },
  { id: "117", name: "신공덕동", isSelected: false, districtId: "13" },
  { id: "118", name: "신수동", isSelected: false, districtId: "13" },
  { id: "119", name: "아현동", isSelected: false, districtId: "13" },
  { id: "120", name: "연남동", isSelected: false, districtId: "13" },
  { id: "121", name: "염리동", isSelected: false, districtId: "13" },
  { id: "122", name: "용강동", isSelected: false, districtId: "13" },
  { id: "123", name: "중동", isSelected: false, districtId: "13" },
  { id: "124", name: "창전동", isSelected: false, districtId: "13" },
  { id: "125", name: "토정동", isSelected: false, districtId: "13" },
  { id: "126", name: "합정동", isSelected: false, districtId: "13" },
  { id: "127", name: "현석동", isSelected: false, districtId: "13" },

  // 서대문구 (id: "14")
  { id: "128", name: "남가좌동", isSelected: false, districtId: "14" },
  { id: "129", name: "냉천동", isSelected: false, districtId: "14" },
  { id: "130", name: "대신동", isSelected: false, districtId: "14" },
  { id: "131", name: "대현동", isSelected: false, districtId: "14" },
  { id: "132", name: "모래내고개동", isSelected: false, districtId: "14" },
  { id: "133", name: "미근동", isSelected: false, districtId: "14" },
  { id: "134", name: "북가좌동", isSelected: false, districtId: "14" },
  { id: "135", name: "북아현동", isSelected: false, districtId: "14" },
  { id: "136", name: "신촌동", isSelected: false, districtId: "14" },
  { id: "137", name: "연희동", isSelected: false, districtId: "14" },
  { id: "138", name: "영천동", isSelected: false, districtId: "14" },
  { id: "139", name: "옥천동", isSelected: false, districtId: "14" },
  { id: "140", name: "창천동", isSelected: false, districtId: "14" },
  { id: "141", name: "천연동", isSelected: false, districtId: "14" },
  { id: "142", name: "충정로동", isSelected: false, districtId: "14" },
  { id: "143", name: "합동", isSelected: false, districtId: "14" },
  { id: "144", name: "현저동", isSelected: false, districtId: "14" },
  { id: "145", name: "홍은동", isSelected: false, districtId: "14" },
  { id: "146", name: "홍제동", isSelected: false, districtId: "14" },

  // 서초구 (id: "15")
  { id: "147", name: "내곡동", isSelected: false, districtId: "15" },
  { id: "148", name: "반포동", isSelected: false, districtId: "15" },
  { id: "149", name: "방배동", isSelected: false, districtId: "15" },
  { id: "150", name: "서초동", isSelected: false, districtId: "15" },
  { id: "151", name: "신원동", isSelected: false, districtId: "15" },
  { id: "152", name: "양재동", isSelected: false, districtId: "15" },
  { id: "153", name: "염곡동", isSelected: false, districtId: "15" },
  { id: "154", name: "원지동", isSelected: false, districtId: "15" },
  { id: "155", name: "우면동", isSelected: false, districtId: "15" },
  { id: "156", name: "원터동", isSelected: false, districtId: "15" },
  { id: "157", name: "잠원동", isSelected: false, districtId: "15" },

  // 성동구 (id: "16")
  { id: "158", name: "금고동", isSelected: false, districtId: "16" },
  { id: "159", name: "도선동", isSelected: false, districtId: "16" },
  { id: "160", name: "마장동", isSelected: false, districtId: "16" },
  { id: "161", name: "사근동", isSelected: false, districtId: "16" },
  { id: "162", name: "상왕십리동", isSelected: false, districtId: "16" },
  { id: "163", name: "성수동", isSelected: false, districtId: "16" },
  { id: "164", name: "송정동", isSelected: false, districtId: "16" },
  { id: "165", name: "신당동", isSelected: false, districtId: "16" },
  { id: "166", name: "옥수동", isSelected: false, districtId: "16" },
  { id: "167", name: "용답동", isSelected: false, districtId: "16" },
  { id: "168", name: "왕십리동", isSelected: false, districtId: "16" },
  { id: "169", name: "응봉동", isSelected: false, districtId: "16" },
  { id: "170", name: "자양동", isSelected: false, districtId: "16" },
  { id: "171", name: "행당동", isSelected: false, districtId: "16" },
  { id: "172", name: "홍익동", isSelected: false, districtId: "16" },

  // 성북구 (id: "17")
  { id: "173", name: "길음동", isSelected: false, districtId: "17" },
  { id: "174", name: "돈암동", isSelected: false, districtId: "17" },
  { id: "175", name: "동선동", isSelected: false, districtId: "17" },
  { id: "176", name: "보문동", isSelected: false, districtId: "17" },
  { id: "177", name: "삼선동", isSelected: false, districtId: "17" },
  { id: "178", name: "상월곡동", isSelected: false, districtId: "17" },
  { id: "179", name: "석관동", isSelected: false, districtId: "17" },
  { id: "180", name: "성북동", isSelected: false, districtId: "17" },
  { id: "181", name: "안암동", isSelected: false, districtId: "17" },
  { id: "182", name: "월곡동", isSelected: false, districtId: "17" },
  { id: "183", name: "정릉동", isSelected: false, districtId: "17" },
  { id: "184", name: "종암동", isSelected: false, districtId: "17" },
  { id: "185", name: "하월곡동", isSelected: false, districtId: "17" },

  // 송파구 (id: "18")
  { id: "186", name: "가락동", isSelected: false, districtId: "18" },
  { id: "187", name: "거여동", isSelected: false, districtId: "18" },
  { id: "188", name: "마천동", isSelected: false, districtId: "18" },
  { id: "189", name: "문정동", isSelected: false, districtId: "18" },
  { id: "190", name: "방이동", isSelected: false, districtId: "18" },
  { id: "191", name: "삼전동", isSelected: false, districtId: "18" },
  { id: "192", name: "석촌동", isSelected: false, districtId: "18" },
  { id: "193", name: "송파동", isSelected: false, districtId: "18" },
  { id: "194", name: "신천동", isSelected: false, districtId: "18" },
  { id: "195", name: "오금동", isSelected: false, districtId: "18" },
  { id: "196", name: "오륜동", isSelected: false, districtId: "18" },
  { id: "197", name: "잠실동", isSelected: false, districtId: "18" },
  { id: "198", name: "장지동", isSelected: false, districtId: "18" },
  { id: "199", name: "풍납동", isSelected: false, districtId: "18" },

  // 양천구 (id: "19")
  { id: "200", name: "목동", isSelected: false, districtId: "19" },
  { id: "201", name: "신월동", isSelected: false, districtId: "19" },
  { id: "202", name: "신정동", isSelected: false, districtId: "19" },

  // 영등포구 (id: "20")
  { id: "203", name: "당산동", isSelected: false, districtId: "20" },
  { id: "204", name: "대림동", isSelected: false, districtId: "20" },
  { id: "205", name: "도림동", isSelected: false, districtId: "20" },
  { id: "206", name: "문래동", isSelected: false, districtId: "20" },
  { id: "207", name: "신길동", isSelected: false, districtId: "20" },
  { id: "208", name: "양평동", isSelected: false, districtId: "20" },
  { id: "209", name: "여의도동", isSelected: false, districtId: "20" },
  { id: "210", name: "영등포동", isSelected: false, districtId: "20" },

  // 용산구 (id: "21")
  { id: "211", name: "갈월동", isSelected: false, districtId: "21" },
  { id: "212", name: "남영동", isSelected: false, districtId: "21" },
  { id: "213", name: "도원동", isSelected: false, districtId: "21" },
  { id: "214", name: "동빙고동", isSelected: false, districtId: "21" },
  { id: "215", name: "동자동", isSelected: false, districtId: "21" },
  { id: "216", name: "보광동", isSelected: false, districtId: "21" },
  { id: "217", name: "서빙고동", isSelected: false, districtId: "21" },
  { id: "218", name: "신계동", isSelected: false, districtId: "21" },
  { id: "219", name: "용문동", isSelected: false, districtId: "21" },
  { id: "220", name: "용산동", isSelected: false, districtId: "21" },
  { id: "221", name: "원효로동", isSelected: false, districtId: "21" },
  { id: "222", name: "이촌동", isSelected: false, districtId: "21" },
  { id: "223", name: "이태원동", isSelected: false, districtId: "21" },
  { id: "224", name: "전자상가동", isSelected: false, districtId: "21" },
  { id: "225", name: "청파동", isSelected: false, districtId: "21" },
  { id: "226", name: "한강로동", isSelected: false, districtId: "21" },
  { id: "227", name: "한남동", isSelected: false, districtId: "21" },
  { id: "228", name: "효창동", isSelected: false, districtId: "21" },
  { id: "229", name: "후암동", isSelected: false, districtId: "21" },

  // 은평구 (id: "22")
  { id: "230", name: "갈현동", isSelected: false, districtId: "22" },
  { id: "231", name: "구산동", isSelected: false, districtId: "22" },
  { id: "232", name: "녹번동", isSelected: false, districtId: "22" },
  { id: "233", name: "대조동", isSelected: false, districtId: "22" },
  { id: "234", name: "불광동", isSelected: false, districtId: "22" },
  { id: "235", name: "수색동", isSelected: false, districtId: "22" },
  { id: "236", name: "신사동", isSelected: false, districtId: "22" },
  { id: "237", name: "역촌동", isSelected: false, districtId: "22" },
  { id: "238", name: "응암동", isSelected: false, districtId: "22" },
  { id: "239", name: "증산동", isSelected: false, districtId: "22" },
  { id: "240", name: "진관동", isSelected: false, districtId: "22" },

  // 종로구 (id: "23") - 주요 동들만 선별
  { id: "241", name: "가회동", isSelected: false, districtId: "23" },
  { id: "242", name: "경운동", isSelected: false, districtId: "23" },
  { id: "243", name: "계동", isSelected: false, districtId: "23" },
  { id: "244", name: "공평동", isSelected: false, districtId: "23" },
  { id: "245", name: "구기동", isSelected: false, districtId: "23" },
  { id: "246", name: "낙원동", isSelected: false, districtId: "23" },
  { id: "247", name: "동숭동", isSelected: false, districtId: "23" },
  { id: "248", name: "명륜동", isSelected: false, districtId: "23" },
  { id: "249", name: "무악동", isSelected: false, districtId: "23" },
  { id: "250", name: "부암동", isSelected: false, districtId: "23" },
  { id: "251", name: "사직동", isSelected: false, districtId: "23" },
  { id: "252", name: "삼청동", isSelected: false, districtId: "23" },
  { id: "253", name: "안국동", isSelected: false, districtId: "23" },
  { id: "254", name: "이화동", isSelected: false, districtId: "23" },
  { id: "255", name: "인사동", isSelected: false, districtId: "23" },
  { id: "256", name: "익선동", isSelected: false, districtId: "23" },
  { id: "257", name: "재동", isSelected: false, districtId: "23" },
  { id: "258", name: "종로동", isSelected: false, districtId: "23" },
  { id: "259", name: "청운동", isSelected: false, districtId: "23" },
  { id: "260", name: "통인동", isSelected: false, districtId: "23" },
  { id: "261", name: "평창동", isSelected: false, districtId: "23" },
  { id: "262", name: "혜화동", isSelected: false, districtId: "23" },
  { id: "263", name: "효자동", isSelected: false, districtId: "23" },

  // 중구 (id: "24") - 주요 동들만 선별
  { id: "264", name: "광희동", isSelected: false, districtId: "24" },
  { id: "265", name: "남산동", isSelected: false, districtId: "24" },
  { id: "266", name: "남창동", isSelected: false, districtId: "24" },
  { id: "267", name: "다산동", isSelected: false, districtId: "24" },
  { id: "268", name: "동화동", isSelected: false, districtId: "24" },
  { id: "269", name: "방산동", isSelected: false, districtId: "24" },
  { id: "270", name: "봉래동", isSelected: false, districtId: "24" },
  { id: "271", name: "소공동", isSelected: false, districtId: "24" },
  { id: "272", name: "신당동", isSelected: false, districtId: "24" },
  { id: "273", name: "을지로동", isSelected: false, districtId: "24" },
  { id: "274", name: "인현동", isSelected: false, districtId: "24" },
  { id: "275", name: "장충동", isSelected: false, districtId: "24" },
  { id: "276", name: "정동", isSelected: false, districtId: "24" },
  { id: "277", name: "중림동", isSelected: false, districtId: "24" },
  { id: "278", name: "필동", isSelected: false, districtId: "24" },
  { id: "279", name: "회현동", isSelected: false, districtId: "24" },
  { id: "280", name: "황학동", isSelected: false, districtId: "24" },

  // 중랑구 (id: "25")
  { id: "281", name: "면목동", isSelected: false, districtId: "25" },
  { id: "282", name: "묵동", isSelected: false, districtId: "25" },
  { id: "283", name: "망우동", isSelected: false, districtId: "25" },
  { id: "284", name: "상봉동", isSelected: false, districtId: "25" },
  { id: "285", name: "신내동", isSelected: false, districtId: "25" },
  { id: "286", name: "중화동", isSelected: false, districtId: "25" },
];
